config/routes.rb
Rails.application.routes.draw do
  get 'bookings/create'
  devise_for :users
  root to: 'toys#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :toys, except: :destroy do
    resources :bookings, only: %i[new create edit update show]
    resources :reviews, only: %i[new create edit update]
  end
  resources :bookings, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :toy
  belongs_to :user
  validates :date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :toy
  has_many :users
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/toy.rb
class Toy < ApplicationRecord
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @toy = Toy.find(params[:toy_id])
    @booking = Booking.new(booking_params)
    @booking.toy = @toy
    @booking.user = current_user
    if @booking.save
      render :show
    else
      redirect_to toy_path(@toy)
    end
  end

  def update
  end

  def show
    @booking = Booking.find_by(toy: params[:toy_id], user: current_user)
  end

  def destroy
  end

  private

  def booking_params
    params.require(:booking).permit(:date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @toy = Toy.find(params[:toy_id])
    @review = @Review.new
  end

  def create
    @toy = Toy.find(params[:toy_id])
    @review = Review.new(review_params)
    @review.toy = @toy
    if @review.save
      redirect_to toy_path(@toy)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to toy_path
  end


private

  def review_params
    params.require(:review).permit(:content, :rating, :toy_id)
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :set_toy, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!

  def index
    @toys = Toy.all
  end

  def show
    @toy = Toy.find(params[:id])
    @booking = Booking.new
    @reviews = Review.where(toy: @toy)
    @review = Review.new(toy: @toy)
  end

  def new
    @toy = Toy.new
  end

  def create
    @toy = Toy.new(toy_params)
    if @toy.save
      redirect_to root_path(@toy)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @toy.update(toy_params)
    redirect_to toy_path(@toy)
  end

  private

  def set_toy
    @toy = Toy.find(params[:id])
  end

  def toy_params
    params.require(:toy).permit(:name, :price, :color, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<h1>Votre réservation est validée</h1>
<%= @booking.toy.name %>
<%= @booking.date %>
<%= @booking.toy.color %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toysaurus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%# <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/toys/_form.html.erb
<div class="container"><%= simple_form_for @toy do |f| %>
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <%= f.input :name, label: 'Name of toy', error: 'Username is mandatory, please specify one' %>
    <%= f.input :price %>
    <%= f.input :color %>
    <%#= f.input :description %>
    <%#= f.association :category %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn-success" %>
    <% end %>
  </div>
</div>

app/views/toys/edit.html.erb
<%= render 'form', toy: @toy %>

app/views/toys/index.html.erb
<h1>List des jouets</h1>

<div class="cards">
      <% @toys.each do |toy| %>
        <%= link_to toy_path(toy), :action => 'go' do %>
          <div class="card-category" style="background-image: url(<%= toy.photo.attached? ? cl_image_path(toy.photo.key) : asset_path("ranger.jpg")%>)">
            <h3 class="title-card"><%= toy.name %></h3>
          </div>
        <% end %>
      <% end %>
</div>
<div>
    <%= link_to 'Add a toy', new_toy_path, class: "btn-add btn btn-primary"  %>
  </div>
<div class="container-btn">
</div>

app/views/toys/new.html.erb
<%= render 'form', toy: @toy %>

app/views/toys/show.html.erb
<div class="container-show" style="background-image: url(<%= @toy.photo.attached? ? cl_image_path(@toy.photo.key) : asset_path("ranger.jpg")%>)">

  <h1><%= @toy.name %></h1>
  <h2><%= @toy.price %>€/jour</h2>
  <h3>Couleur : <%= @toy.color %></h3>
</div>


<%= link_to "Modifier", edit_toy_path(@toy) %>
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Réserver</h2>

    <%= simple_form_for [@toy, @booking], method: "post" do |f| %>
      <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Réserver", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>


<div class="m-5 p-5">
  <div class="card mb-2">
    <div class="card-body mx-2">
      <%= simple_form_for([@toy, @review], remote: true) do  |f| %>
        <%= f.input :content, placeholder: "Laissez un avis"%>
        <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "Laissez une note au jouet", input_html: { data: { controller: "jquery-bar-rating" } } %>
        <%= f.submit class:"btn btn-warning" %>
      <% end %>
  </div>
</div>

<% @reviews.each do |review|%>
    <div class="card-product mx-5 bg-white">
      <div class="card-product-infos">
      <p><%= review.rating %></p>
         <p><%= review.content %></p>
      </div>
    </div>
  <% end %>